server:
  id: "order-service-1"
  name: "order-service"
  host: "127.0.0.1"
  port: 8080
serviceRegistry:
  bootstrap: "139.59.77.98:2181"
messageBroker:
  bootstrap: "139.59.77.98:9092"
  retries: 10
  acks: "all"
  interval: 100