server:
  id: "order-service-1"
  name: "order-service"
  port: 8081
serviceRegistry:
  bootstrap: "localhost:2181"
messageBroker:
  bootstrap: "localhost:9092"
  retries: 10
  acks: "all"
  interval: 100